export const mapAuthError = (code: string | undefined): string => {
  if (!code) return "Ocurrió un error inesperado. Por favor, inténtalo de nuevo.";

  const errorMessages: Record<string, string> = {
    // Auth Error Codes
    anonymous_provider_disabled: "Los inicios de sesión anónimos están deshabilitados.",
    bad_code_verifier: "Error de verificación de código. Inténtalo de nuevo.",
    bad_json: "El formato de la solicitud no es válido.",
    bad_jwt: "El token de autorización no es válido.",
    bad_oauth_callback: "Error en la respuesta del proveedor de inicio de sesión.",
    bad_oauth_state: "El estado de inicio de sesión no tiene el formato correcto.",
    captcha_failed: "No se pudo verificar el CAPTCHA. Inténtalo de nuevo.",
    conflict: "Conflicto en la base de datos, demasiadas solicitudes a la vez. Inténtalo más tarde.",
    email_address_invalid: "La dirección de correo electrónico no es válida o es de prueba.",
    email_address_not_authorized: "No estás autorizado para enviar correos a esta dirección.",
    email_conflict_identity_not_deletable: "Esta cuenta está vinculada a un correo ya en uso. Contacta a soporte.",
    email_exists: "La dirección de correo electrónico ya se encuentra registrada.",
    email_not_confirmed: "Tu dirección de correo electrónico aún no está confirmada. Revisa tu bandeja de entrada.",
    email_provider_disabled: "El registro mediante correo electrónico y contraseña está deshabilitado.",
    flow_state_expired: "El tiempo para iniciar sesión ha caducado. Inténtalo de nuevo.",
    flow_state_not_found: "La solicitud de inicio de sesión ya no existe. Inténtalo de nuevo.",
    hook_payload_invalid_content_type: "La solicitud de autenticación es inválida.",
    hook_payload_over_size_limit: "La solicitud de autenticación supera el límite de tamaño.",
    hook_timeout: "El servidor de autenticación tardó demasiado en responder.",
    hook_timeout_after_retry: "El servidor de autenticación no respondió después de varios intentos.",
    identity_already_exists: "Esta identidad ya está vinculada a un usuario.",
    identity_not_found: "La identidad de inicio de sesión no existe o fue eliminada.",
    insufficient_aal: "Se requiere autenticación multifactor para continuar.",
    invalid_credentials: "El correo electrónico o la contraseña son incorrectos.",
    invite_not_found: "La invitación ha caducado o ya ha sido utilizada.",
    manual_linking_disabled: "La vinculación manual de cuentas no está habilitada.",
    mfa_challenge_expired: "El tiempo para la verificación multifactor ha caducado. Inténtalo de nuevo.",
    mfa_factor_name_conflict: "Ya existe un método de verificación con este nombre.",
    mfa_factor_not_found: "El método de verificación ya no existe.",
    mfa_ip_address_mismatch: "La dirección IP cambió durante la configuración de seguridad.",
    mfa_phone_enroll_not_enabled: "La verificación por teléfono no está habilitada.",
    mfa_phone_verify_not_enabled: "El inicio de sesión por teléfono no está habilitado.",
    mfa_totp_enroll_not_enabled: "La configuración de autenticación TOTP no está habilitada.",
    mfa_totp_verify_not_enabled: "El inicio de sesión mediante TOTP no está habilitado.",
    mfa_verification_failed: "Código de verificación incorrecto.",
    mfa_verification_rejected: "La verificación adicional fue rechazada.",
    mfa_verified_factor_exists: "Ya tienes un número de teléfono verificado. Elimínalo para registrar uno nuevo.",
    mfa_web_authn_enroll_not_enabled: "La verificación web no está habilitada.",
    mfa_web_authn_verify_not_enabled: "El inicio de sesión con verificación web no está habilitado.",
    no_authorization: "No tienes autorización para realizar esta acción.",
    not_admin: "No tienes permisos de administrador para realizar esta acción.",
    oauth_provider_not_supported: "Este método de inicio de sesión no está habilitado.",
    otp_disabled: "El inicio de sesión con código temporal está deshabilitado.",
    otp_expired: "El código temporal ha caducado. Solicita uno nuevo.",
    over_email_send_rate_limit: "Has solicitado demasiados correos. Espera un momento antes de volver a intentarlo.",
    over_request_rate_limit: "Has realizado demasiadas solicitudes. Espera unos minutos e inténtalo de nuevo.",
    over_sms_send_rate_limit: "Has solicitado demasiados mensajes SMS. Espera un momento antes de volver a intentarlo.",
    phone_exists: "El número de teléfono ya se encuentra registrado.",
    phone_not_confirmed: "Tu número de teléfono aún no está confirmado.",
    phone_provider_disabled: "El registro mediante teléfono está deshabilitado.",
    provider_disabled: "Este proveedor de inicio de sesión está deshabilitado.",
    provider_email_needs_verification: "Debes verificar tu correo electrónico para usar este método de inicio de sesión.",
    reauthentication_needed: "Por seguridad, necesitas volver a iniciar sesión para cambiar tu contraseña.",
    reauthentication_not_valid: "El código de reautenticación es incorrecto. Inténtalo de nuevo.",
    refresh_token_already_used: "Tu sesión ha caducado. Por favor, inicia sesión de nuevo.",
    refresh_token_not_found: "No se encontró tu sesión. Por favor, inicia sesión de nuevo.",
    request_timeout: "El servidor tardó demasiado en responder. Vuelva a intentarlo.",
    same_password: "La nueva contraseña debe ser diferente a la actual.",
    saml_assertion_no_email: "El proveedor de inicio de sesión no envió tu correo electrónico.",
    saml_assertion_no_user_id: "El proveedor de inicio de sesión no envió tu identificador de usuario.",
    saml_entity_id_mismatch: "El identificador del proveedor no coincide.",
    saml_idp_already_exists: "Este proveedor de identidad ya está registrado.",
    saml_idp_not_found: "No se encontró el proveedor de identidad para iniciar sesión.",
    saml_metadata_fetch_failed: "No se pudo obtener la información del proveedor de identidad.",
    saml_provider_disabled: "El inicio de sesión corporativo no está habilitado.",
    saml_relay_state_expired: "El tiempo de inicio de sesión corporativo ha caducado. Inténtalo de nuevo.",
    saml_relay_state_not_found: "La solicitud de inicio de sesión corporativo ya no existe. Inténtalo de nuevo.",
    session_expired: "Tu sesión ha caducado por inactividad. Por favor, inicia sesión de nuevo.",
    session_not_found: "Tu sesión ya no existe. Por favor, inicia sesión de nuevo.",
    signup_disabled: "Los registros de nuevas cuentas están deshabilitados temporalmente.",
    single_identity_not_deletable: "No puedes eliminar este método de acceso porque es el único que tienes.",
    sms_send_failed: "No se pudo enviar el mensaje SMS. Inténtalo más tarde.",
    sso_domain_already_exists: "Este dominio ya está registrado para otro proveedor.",
    sso_provider_not_found: "No se encontró el proveedor corporativo.",
    too_many_enrolled_mfa_factors: "Has alcanzado el límite de métodos de seguridad registrados.",
    unexpected_audience: "La solicitud no es válida para este servicio.",
    unexpected_failure: "Ocurrió un error inesperado en el servidor. Inténtalo más tarde.",
    user_already_exists: "Ya existe un usuario con este correo electrónico",
    user_banned: "Tu cuenta ha sido suspendida temporalmente.",
    user_not_found: "El usuario no existe o fue eliminado.",
    user_sso_managed: "No puedes actualizar esta información porque tu cuenta es corporativa.",
    validation_failed: "Los datos proporcionados no son válidos.",
    weak_password: "La contraseña es muy débil. Utiliza una más segura.",
    
    // Database Error Codes (PostgreSQL)
    "23505": "Ya existe un registro con esta información (por ejemplo, el correo ya está en uso).",
    "23503": "La información ingresada no es válida o hace referencia a un dato que no existe.",
    "23502": "Falta información obligatoria para completar el registro.",
  };

  return errorMessages[code] || "Ocurrió un error inesperado. Por favor, inténtalo de nuevo.";
};
